DROP DATABASE IF EXISTS NetflixLibrosBD;
CREATE DATABASE NetflixLibrosBD;
USE NetflixLibrosBD;

CREATE TABLE Usuario(
    idUsuario INT AUTO_INCREMENT PRIMARY KEY,
    Email VARCHAR(100) NOT NULL UNIQUE,
    Password VARCHAR(100) NOT NULL,
	Rol INT NULL
);
INSERT INTO Usuario ( Email, Password, Rol)
VALUES ("admin@gmail.com" , "PrP+ZrMeO00Q+nC1ytSccRIpSvauTkdqHEBRVdRaoSE=",1);


CREATE TABLE Libro (
    IdLibro INT AUTO_INCREMENT PRIMARY KEY,
    Titulo VARCHAR(200) NOT NULL,
    Autor VARCHAR(150) NOT NULL,
    Genero VARCHAR(100),
    Sinopsis TEXT,
    Imagen VARCHAR(300),
    UrlLibro VARCHAR (300)
);


INSERT INTO Libro ( Titulo, Autor, Genero, Sinopsis, Imagen, UrlLibro )
VALUES 
('La sombra del viento', 'Carlos Ruiz Zafón', 'Misterio, suspenso, drama y romance', 'En La sombra del viento, un niño llamado Daniel Sempere, llevado por su padre al Cementerio de los Libros Olvidados, encuentra un misterioso libro que marca el inicio de una odisea en la Barcelona de posguerra', '/Imagenes/9c702221-d67a-4bda-b7a7-c8e5a51aa16a.webp', 'https://moodle2.units.it/pluginfile.php/729086/mod_resource/content/1/Ruiz-Zafon-Carlos-La-Sombra-Del-Viento_54Y.pdf'),
('El asesinato de Platón', 'Marcos Chicot', 'Suspenso, misterio y ficción historica', '"El asesinato de Platón, de Marcos Chicot, es un thriller histórico ambientado en la Grecia clásica que combina intriga política, filosofía y acción, centrado en el discípulo de Platón, Altea, quien lucha contra enemigos ocultos en su propia casa..."', '/Imagenes/78c1c6fd-73e5-4bb4-8bf0-f632716cc27e.webp', 'https://proassetspdlcom.cdnstatics2.com/usuaris/libros_contenido/arxius/45/44593_1_El_asesinato_de_Platon.pdf'),
('El lago secreto', 'Karen Inglis', 'Ficcion de aventura', 'Cuenta la historia de los hermanos Stella y Tom, quienes, tras mudarse, descubren un misterioso túnel cerca de su nueva casa que los lleva a un lago que existe en el pasado, permitiéndoles viajar en el tiempo y resolver un misterio que conecta el prese...', '/Imagenes/fd75eab1-b3d9-4ab6-aa3e-8694287fbca3.jpg', 'https://proassetspdlcom.cdnstatics2.com/usuaris/libros_contenido/arxius/56/55388_El_lago_secreto.pdf'),
('El Ángel de la Ciudad', 'Eva García Sáenz de Urturi', 'Misterio, ficción y suspenso', 'El inspector Kraken investiga un incendio en Venecia que recuerda un suceso pasado de su madre, Ítaca, mientras su pasado y futuro chocan, explorando un doble misterio que envuelve el origen de su familia, el amor por los libros y un peligroso "ángel d..."', '/Imagenes/a850cd6b-2145-4397-a41a-73fded3b1f98.jpg', 'https://proassets.planetadelibros.com.ar/usuaris/libros_contenido/arxius/53/53000_TPCW_El%20angel%20de%20la%20ciudad.pdf'),
('La Casa de los Espíritus', 'Isabel Allende', 'Realismo mágico', 'La casa de los espíritus narra la saga de la familia Trueba a lo largo de cuatro generaciones en un país latinoamericano, entrelazando sus dramas personales —amor, odio, política— con la tumultuosa historia del siglo XX, marcada por la injusticia ...', '/Imagenes/0b3cecf6-bb9d-4b61-a2b9-637249776b02.jpg', 'https://www.suneo.mx/literatura/subidas/Isabel%20Allende%20La%20Casa%20de%20los%20Esp%C3%ADritus.pdf'),
( 'Alas de sangre (Empíreo 1)', 'Rebecca Yarros', 'Fantasía Romántica', 'Alas de sangre sigue a Violet Sorrengail, una joven que, en contra de sus deseos de ser escriba, debe ingresar a la peligrosa Academia de Guerra de Basgiath para convertirse en jinete de dragones por orden de su madre.', '/Imagenes/38ad675c-4789-433a-ab81-b2ca21d59df7.jpg', 'https://proassets.planetadelibros.com.ar/usuaris/libros_contenido/arxius/55/54061_TPC_Alas%20de%20sangre.pdf'),
('Alas de hierro (Empíreo 2)', 'Rebecca Yarros', 'Fantasía', 'Es la secuela de Alas de Sangre, en la que Violet Sorrengail debe continuar su entrenamiento en el brutal Colegio de Guerra de Basgiath para convertirse en jinete de dragón', '/Imagenes/62611e0a-9e02-49d2-af31-702678c788be.jpg', 'https://proassetspdlcom.cdnstatics2.com/usuaris/libros_contenido/arxius/56/55949_Alas_de_hierro.pdf'),
('El poder de confiar en ti', 'Curro Cañete', 'Autoayuda', 'Es un libro de autoayuda que te enseña a ser tu propio guía y coach, proporcionando pautas y ejercicios para entrenar tu mente, superar miedos y trampas mentales, y alcanzar tus deseos y aspiraciones, basándose en la idea de que la confianza es un mú...', '/Imagenes/8856c2a5-dfae-4e64-861e-e2dee6bfce6b.jpg','https://pladlibroscl0.cdnstatics.com/libros_contenido_extra/41/40225_El_poder_de_confiar_en_ti.pdf'),
('El principito', 'Antoine de Saint-Exupéry', 'Misterio, ciencia ficción fantástica','El Principito narra el encuentro poético y filosófico entre un aviador varado en el desierto del Sahara y un pequeño príncipe llegado de un asteroide minúsculo, el B-612, quien comparte sus viajes por otros planetas y sus reflexiones sobre la vida, ...','/Imagenes/5df357c1-7bde-418a-81d9-1f327be3d311.jpg','https://web.seducoahuila.gob.mx/biblioweb/upload/el%20principito.pdf'),
('El tiempo entre costuras', 'María Dueñas', 'Ficción histórica','El tiempo entre costuras narra la historia de Sira Quiroga, una joven modista que abandona Madrid en 1936, arrastrada por el amor a un hombre al que apenas conoce. Tras ser abandonada, se ve obligada a empezar una nueva vida en Tánger, donde funda un ta...','/Imagenes/b78ddd85-f2d6-47b4-8f25-c22bf289a2bd.jpg','https://premisrecerca.uvic.cat/sites/default/files/webform/el_tiempo_entre_costuras.pdf'),
( 'El matadero', 'Esteban Echeverría', 'Ficción','El Matadero de Esteban Echeverría es un cuento clave del romanticismo argentino que denuncia la barbarie y violencia política en Buenos Aires bajo el gobierno de Rosas, ambientado en un matadero durante la Cuaresma, donde la escasez de carne y la hambr...','/Imagenes/4276c73b-8b30-4b6f-aab2-7f541f5a7031.jpg','https://idartesencasa.gov.co/sites/default/files/libros_pdf/111.%20El%20Matadero.pdf'), 
('Cadáver exquisito', 'Agustina Bazterrica', 'Ciencia ficción, suspenso, novela psicológica','Cadáver Exquisito, la novela de Agustina Bazterrica, describe un mundo distópico donde un virus letal para los animales lleva a la legalización del canibalismo. La sociedad se divide entre quienes consumen y quienes son consumidos, y la trama sigue a ...','/Imagenes/6beb09e9-2844-4ac0-980a-2d192e1e22f6.png','https://info-biblioteca.mincyt.gob.ve/wp-content/uploads/2025/06/Cadaver-exquisito-Agustina-Bazterrica.pdf'),
( 'Robin Hood', 'Howard Pyle', 'Romances, novelas históricas, narrativa de aventuras','Robin Hood trata de un héroe popular inglés del folclore medieval que, junto a sus "hombres alegres" en el bosque de Sherwood, roba a los ricos para dárselo a los pobres, luchando contra la opresión del Sheriff de Nottingham y el Príncipe Juan mient...','/Imagenes/fbf1beac-b92a-467e-9a06-d47142bf93e4.jpg','https://buenosaires.gob.ar/areas/educacion/recursos/lengua/pdf/texto_robin_hood.pdf'),
('Los juegos del hambre','Suzanne Collins','Ciencia Ficción, Aventura, Drama y Romance','Presenta a Katniss Everdeen, una adolescente de 16 años en la nación postapocalíptica de Panem, donde el rico Capitolio obliga a 12 distritos empobrecidos a enviar un chico y una chica ("tributos") a un combate a muerte televisado anualmente, y Katniss...','/Imagenes/600cf839-89f9-446b-9220-9d8e1d60f755.webp','https://fhs.trusd.net/documents/Library/Ebooks/the%20hunger%20games%20in%20spanish.pdf'),
('La isla misteriosa', 'Julio Verne', 'Ficción de aventuras, novela científica','La isla misteriosa es una novela de Julio Verne sobre cinco hombres que escapan de la Guerra de Secesión en un globo aerostático y terminan naufragando en una isla desierta en el Pacífico. Liderados por el ingeniero Cyrus Smith, utilizan su conocimiento...','/Imagenes/61760eb1-ef5e-4aa1-8da7-4f90db78b5ea.jpg','https://portalacademico.cch.unam.mx/materiales/al/cont/tall/tlriid/tlriid4/circuloLectores/docs/la_isla_misteriosa.pdf'),
('Harry Potter y la piedra filosofal', 'J. K. Rowling', 'Literatura fantástica, sobrenaturales, mágicos','Harry, un niño huérfano que descubre en su undécimo cumpleaños que es un mago. Es invitado a asistir a la escuela de hechicería Hogwarts, donde hace amigos como Ron y Hermione. Allí, los tres descubren que alguien intenta robar la Piedra Filosofal...','/Imagenes/027db0ba-4b02-47f2-b5d8-dde105f6c79e.jpg','https://biblioteca-digital.universidadcolumbia.edu.mx/acervo/LITERATURA/Harry_Potter_y_la_Piedra_Filosofal-J_K_Rowling.pdf'),
('El alquimista', 'Paulo Coelho', 'Ficción de aventuras, drama, literatura fantástica','El Alquimista de Paulo Coelho narra el viaje de Santiago, un pastor andaluz que abandona su vida para seguir un sueño sobre un tesoro escondido en las pirámides de Egipto.','/Imagenes/1eeb6f4b-8325-4275-9bf4-f0ea2233d12c.jpg','https://formarse.com.ar/libros/Libros%20para%20descargar%20de%20maestros%20espirituales/El-Alquimista.pdf'),
('El Aleph', 'Jorge Luis Borges', 'Ficción literaria','Trata sobre la experiencia metafísica de ver la totalidad del universo en un punto diminuto, explorando temas como la infinitud, la percepción, la memoria y la insuficiencia del lenguaje humano...','/Imagenes/1149a134-cc18-4760-9390-7d48b894546f.jpg','https://ens9004-infd.mendoza.edu.ar/sitio/literatura-argentina/upload/0010-_BORGES_J.L._-_El-Aleph.pdf'),
('El conde de Montecristo', 'Alexandre Dumas', 'Ficción de aventuras, ficción histórica','Es una novela de Alexandre Dumas sobre Edmundo Dantés, un joven marinero que es víctima de una conspiración y encarcelado injustamente. Tras escapar de prisión, encuentra un tesoro y regresa como el conde de Montecristo para vengarse...','/Imagenes/7ead7cc9-e6c5-401d-8e42-7cc4707de5de.jpg','https://www.imprentanacional.go.cr/editorialdigital/libros/literatura%20universal/el_conde_de_montecristo_edincr.pdf'),
('El señor de los anillos', 'J. R. R. Tolkien', 'Literatura fantástica, ficción de aventuras, Romance de caballería','El Señor de los Anillos narra la épica misión de Frodo Bolsón, un hobbit que hereda el Anillo Único, un artefacto maligno forjado por Sauron, y debe destruirlo en el Monte del Destino mientras una guerra se desata...','/Imagenes/5fb5f88a-f757-44a6-8733-68e1f485de4e.jpg','https://web.seducoahuila.gob.mx/biblioweb/upload/J.R.R.%20Tolkien%20La%20Comunidad%20del%20anillo%20I.pdf');
